id: 677b68444c774c05b0a0688beb140532
title: T65
type: translation
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2021-10-21'
  creationid: mabja
  eft-text-id: UT22084-068-016
  xmlns-eft: http://read.84000.co/ns/1.0
